public class Const {

  // constant tag
  public static final int CONSTANT_Class = 7;
  public static final int CONSTANT_Fieldref = 9;
  public static final int CONSTANT_Methodref = 10;
  public static final int CONSTANT_InterfaceMethodref = 11;
  public static final int CONSTANT_String = 8;
  public static final int CONSTANT_Integer = 3;
  public static final int CONSTANT_Float = 4;
  public static final int CONSTANT_Long = 5;
  public static final int CONSTANT_Double = 6;
  public static final int CONSTANT_NameAndType = 12;
  public static final int CONSTANT_Utf8 = 1;
  public static final int CONSTANT_MethodHandle = 15;
  public static final int CONSTANT_MethodType = 16;
  public static final int CONSTANT_InvokeDynamic = 18;

  // class stat
  public static final int CLASS_LOADED = 1;
  public static final int CLASS_LINKED = 2;
  public static final int CLASS_INITING = 3;
  public static final int CLASS_INITED = 4;

  // ACCESS
  public static final int ACC_STATIC = 0x0008;
  public static final int ACC_NATIVE = 0x0100;
  public static final int ACC_INTERFACE = 0x0200;
  public static final int ACC_ABSTRACT = 0x0400;

  // OPCODE
  public static final int OPC_NOP = 0x00; // 00
  public static final int OPC_ACONST_NULL = 0x01; // 01
  public static final int OPC_ICONST_M1 = 0x02; // 02
  public static final int OPC_ICONST_0 = 0x03; // 03
  public static final int OPC_ICONST_1 = 0x04; // 04
  public static final int OPC_ICONST_2 = 0x05; // 05
  public static final int OPC_ICONST_3 = 0x06; // 06
  public static final int OPC_ICONST_4 = 0x07; // 07
  public static final int OPC_ICONST_5 = 0x08; // 08
  public static final int OPC_LCONST_0 = 0x09; // 09
  public static final int OPC_LCONST_1 = 0x0a; // 10
  public static final int OPC_FCONST_0 = 0x0b; // 11
  public static final int OPC_FCONST_1 = 0x0c; // 12
  public static final int OPC_FCONST_2 = 0x0d; // 13
  public static final int OPC_DCONST_0 = 0x0e; // 14
  public static final int OPC_DCONST_1 = 0x0f; // 15
  public static final int OPC_BIPUSH = 0x10; // 16
  public static final int OPC_SIPUSH = 0x11; // 17
  public static final int OPC_LDC = 0x12; // 18
  public static final int OPC_LDC_W = 0x13; // 19
  public static final int OPC_LDC2_W = 0x14; // 20
  public static final int OPC_ILOAD = 0x15; // 21
  public static final int OPC_LLOAD = 0x16; // 22
  public static final int OPC_FLOAD = 0x17; // 23
  public static final int OPC_DLOAD = 0x18; // 24
  public static final int OPC_ALOAD = 0x19; // 25
  public static final int OPC_ILOAD_0 = 0x1a; // 26
  public static final int OPC_ILOAD_1 = 0x1b; // 27
  public static final int OPC_ILOAD_2 = 0x1c; // 28
  public static final int OPC_ILOAD_3 = 0x1d; // 29
  public static final int OPC_LLOAD_0 = 0x1e; // 30
  public static final int OPC_LLOAD_1 = 0x1f; // 31
  public static final int OPC_LLOAD_2 = 0x20; // 32
  public static final int OPC_LLOAD_3 = 0x21; // 33
  public static final int OPC_FLOAD_0 = 0x22; // 34
  public static final int OPC_FLOAD_1 = 0x23; // 35
  public static final int OPC_FLOAD_2 = 0x24; // 36
  public static final int OPC_FLOAD_3 = 0x25; // 37
  public static final int OPC_DLOAD_0 = 0x26; // 38
  public static final int OPC_DLOAD_1 = 0x27; // 39
  public static final int OPC_DLOAD_2 = 0x28; // 40
  public static final int OPC_DLOAD_3 = 0x29; // 41
  public static final int OPC_ALOAD_0 = 0x2a; // 42
  public static final int OPC_ALOAD_1 = 0x2b; // 43
  public static final int OPC_ALOAD_2 = 0x2c; // 44
  public static final int OPC_ALOAD_3 = 0x2d; // 45
  public static final int OPC_IALOAD = 0x2e; // 46
  public static final int OPC_LALOAD = 0x2f; // 47
  public static final int OPC_FALOAD = 0x30; // 48
  public static final int OPC_DALOAD = 0x31; // 49
  public static final int OPC_AALOAD = 0x32; // 50
  public static final int OPC_BALOAD = 0x33; // 51
  public static final int OPC_CALOAD = 0x34; // 52
  public static final int OPC_SALOAD = 0x35; // 53
  public static final int OPC_ISTORE = 0x36; // 54
  public static final int OPC_LSTORE = 0x37; // 55
  public static final int OPC_FSTORE = 0x38; // 56
  public static final int OPC_DSTORE = 0x39; // 57
  public static final int OPC_ASTORE = 0x3a; // 58
  public static final int OPC_ISTORE_0 = 0x3b; // 59
  public static final int OPC_ISTORE_1 = 0x3c; // 60
  public static final int OPC_ISTORE_2 = 0x3d; // 61
  public static final int OPC_ISTORE_3 = 0x3e; // 62
  public static final int OPC_LSTORE_0 = 0x3f; // 63
  public static final int OPC_LSTORE_1 = 0x40; // 64
  public static final int OPC_LSTORE_2 = 0x41; // 65
  public static final int OPC_LSTORE_3 = 0x42; // 66
  public static final int OPC_FSTORE_0 = 0x43; // 67
  public static final int OPC_FSTORE_1 = 0x44; // 68
  public static final int OPC_FSTORE_2 = 0x45; // 69
  public static final int OPC_FSTORE_3 = 0x46; // 70
  public static final int OPC_DSTORE_0 = 0x47; // 71
  public static final int OPC_DSTORE_1 = 0x48; // 72
  public static final int OPC_DSTORE_2 = 0x49; // 73
  public static final int OPC_DSTORE_3 = 0x4a; // 74
  public static final int OPC_ASTORE_0 = 0x4b; // 75
  public static final int OPC_ASTORE_1 = 0x4c; // 76
  public static final int OPC_ASTORE_2 = 0x4d; // 77
  public static final int OPC_ASTORE_3 = 0x4e; // 78
  public static final int OPC_IASTORE = 0x4f; // 79
  public static final int OPC_LASTORE = 0x50; // 80
  public static final int OPC_FASTORE = 0x51; // 81
  public static final int OPC_DASTORE = 0x52; // 82
  public static final int OPC_AASTORE = 0x53; // 83
  public static final int OPC_BASTORE = 0x54; // 84
  public static final int OPC_CASTORE = 0x55; // 85
  public static final int OPC_SASTORE = 0x56; // 86
  public static final int OPC_POP = 0x57; // 87
  public static final int OPC_POP2 = 0x58; // 88
  public static final int OPC_DUP = 0x59; // 89
  public static final int OPC_DUP_X1 = 0x5a; // 90
  public static final int OPC_DUP_X2 = 0x5b; // 91
  public static final int OPC_DUP2 = 0x5c; // 92
  public static final int OPC_DUP2_X1 = 0x5d; // 93
  public static final int OPC_DUP2_X2 = 0x5e; // 94
  public static final int OPC_SWAP = 0x5f; // 95
  public static final int OPC_IADD = 0x60; // 96
  public static final int OPC_LADD = 0x61; // 97
  public static final int OPC_FADD = 0x62; // 98
  public static final int OPC_DADD = 0x63; // 99
  public static final int OPC_ISUB = 0x64; // 100
  public static final int OPC_LSUB = 0x65; // 101
  public static final int OPC_FSUB = 0x66; // 102
  public static final int OPC_DSUB = 0x67; // 103
  public static final int OPC_IMUL = 0x68; // 104
  public static final int OPC_LMUL = 0x69; // 105
  public static final int OPC_FMUL = 0x6a; // 106
  public static final int OPC_DMUL = 0x6b; // 107
  public static final int OPC_IDIV = 0x6c; // 108
  public static final int OPC_LDIV = 0x6d; // 109
  public static final int OPC_FDIV = 0x6e; // 110
  public static final int OPC_DDIV = 0x6f; // 111
  public static final int OPC_IREM = 0x70; // 112
  public static final int OPC_LREM = 0x71; // 113
  public static final int OPC_FREM = 0x72; // 114
  public static final int OPC_DREM = 0x73; // 115
  public static final int OPC_INEG = 0x74; // 116
  public static final int OPC_LNEG = 0x75; // 117
  public static final int OPC_FNEG = 0x76; // 118
  public static final int OPC_DNEG = 0x77; // 119
  public static final int OPC_ISHL = 0x78; // 120
  public static final int OPC_LSHL = 0x79; // 121
  public static final int OPC_ISHR = 0x7a; // 122
  public static final int OPC_LSHR = 0x7b; // 123
  public static final int OPC_IUSHR = 0x7c; // 124
  public static final int OPC_LUSHR = 0x7d; // 125
  public static final int OPC_IAND = 0x7e; // 126
  public static final int OPC_LAND = 0x7f; // 127
  public static final int OPC_IOR = 0x80; // 128
  public static final int OPC_LOR = 0x81; // 129
  public static final int OPC_IXOR = 0x82; // 130
  public static final int OPC_LXOR = 0x83; // 131
  public static final int OPC_IINC = 0x84; // 132
  public static final int OPC_I2L = 0x85; // 133
  public static final int OPC_I2F = 0x86; // 134
  public static final int OPC_I2D = 0x87; // 135
  public static final int OPC_L2I = 0x88; // 136
  public static final int OPC_L2F = 0x89; // 137
  public static final int OPC_L2D = 0x8a; // 138
  public static final int OPC_F2I = 0x8b; // 139
  public static final int OPC_F2L = 0x8c; // 140
  public static final int OPC_F2D = 0x8d; // 141
  public static final int OPC_D2I = 0x8e; // 142
  public static final int OPC_D2L = 0x8f; // 143
  public static final int OPC_D2F = 0x90; // 144
  public static final int OPC_I2B = 0x91; // 145
  public static final int OPC_I2C = 0x92; // 146
  public static final int OPC_I2S = 0x93; // 147
  public static final int OPC_LCMP = 0x94; // 148
  public static final int OPC_FCMPL = 0x95; // 149
  public static final int OPC_FCMPG = 0x96; // 150
  public static final int OPC_DCMPL = 0x97; // 151
  public static final int OPC_DCMPG = 0x98; // 152
  public static final int OPC_IFEQ = 0x99; // 153
  public static final int OPC_IFNE = 0x9a; // 154
  public static final int OPC_IFLT = 0x9b; // 155
  public static final int OPC_IFGE = 0x9c; // 156
  public static final int OPC_IFGT = 0x9d; // 157
  public static final int OPC_IFLE = 0x9e; // 158
  public static final int OPC_IF_ICMPEQ = 0x9f; // 159
  public static final int OPC_IF_ICMPNE = 0xa0; // 160
  public static final int OPC_IF_ICMPLT = 0xa1; // 161
  public static final int OPC_IF_ICMPGE = 0xa2; // 162
  public static final int OPC_IF_ICMPGT = 0xa3; // 163
  public static final int OPC_IF_ICMPLE = 0xa4; // 164
  public static final int OPC_IF_ACMPEQ = 0xa5; // 165
  public static final int OPC_IF_ACMPNE = 0xa6; // 166
  public static final int OPC_GOTO = 0xa7; // 167
  public static final int OPC_JSR = 0xa8; // 168
  public static final int OPC_RET = 0xa9; // 169
  public static final int OPC_TABLESWITCH = 0xaa; // 170
  public static final int OPC_LOOKUPSWITCH = 0xab; // 171
  public static final int OPC_IRETURN = 0xac; // 172
  public static final int OPC_LRETURN = 0xad; // 173
  public static final int OPC_FRETURN = 0xae; // 174
  public static final int OPC_DRETURN = 0xaf; // 175
  public static final int OPC_ARETURN = 0xb0; // 176
  public static final int OPC_RETURN = 0xb1; // 177
  public static final int OPC_GETSTATIC = 0xb2; // 178
  public static final int OPC_PUTSTATIC = 0xb3; // 179
  public static final int OPC_GETFIELD = 0xb4; // 180
  public static final int OPC_PUTFIELD = 0xb5; // 181
  public static final int OPC_INVOKEVIRTUAL = 0xb6; // 182
  public static final int OPC_INVOKESPECIAL = 0xb7; // 183
  public static final int OPC_INVOKESTATIC = 0xb8; // 184
  public static final int OPC_INVOKEINTERFACE = 0xb9; // 185
  public static final int OPC_INVOKEDYNAMIC = 0xba; // 186
  public static final int OPC_NEW = 0xbb; // 187
  public static final int OPC_NEWARRAY = 0xbc; // 188
  public static final int OPC_ANEWARRAY = 0xbd; // 189
  public static final int OPC_ARRAYLENGTH = 0xbe; // 190
  public static final int OPC_ATHROW = 0xbf; // 191
  public static final int OPC_CHECKCAST = 0xc0; // 192
  public static final int OPC_INSTANCEOF = 0xc1; // 193
  public static final int OPC_MONITORENTER = 0xc2; // 194
  public static final int OPC_MONITOREXIT = 0xc3; // 195
  public static final int OPC_WIDE = 0xc4; // 196
  public static final int OPC_MULTIANEWARRAY = 0xc5; // 197
  public static final int OPC_IFNULL = 0xc6; // 198
  public static final int OPC_IFNONNULL = 0xc7; // 199
  public static final int OPC_GOTO_W = 0xc8; // 200
  public static final int OPC_JSR_W = 0xc9; // 201
  public static final int OPC_BREAKPOINT = 0xca; // 202
  public static final int OPC_IMPDEP1 = 0xfe; // 254
  public static final int OPC_IMPDEP2 = 0xff; // 255

  // FRAME
  public static final int FAKE_FRAME = 1;
  public static final int FAKE_FRAME_END = 2;
}
